name: Mirror to sketchshifter_frontend/public/scripts

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    if: github.repository != 'SketchShifter/sketchshifter_frontend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository (sketchshifter_compiler)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Clone destination repository (sketchshifter_frontend)
        run: |
          echo "Cloning sketchshifter_frontend..."
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/SketchShifter/sketchshifter_frontend.git /tmp/destination

          echo "Clearing destination public/scripts..."
          rm -rf /tmp/destination/public/scripts/*
          mkdir -p /tmp/destination/public/scripts

          echo "Copying compiler contents..."
          cp -r . /tmp/destination/public/scripts/

          cd /tmp/destination

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add public/scripts
          git commit -m "Mirror compiler to frontend/public/scripts on $(date)" || echo "No changes to commit"

          echo "Pushing with token..."
          git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/SketchShifter/sketchshifter_frontend.git main


