name: Mirror to Personal Repository

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to personal repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add personal https://${{ secrets.PERSONAL_TOKEN }}@github.com/shimaf4979/mmm.git
          git push --force personal HEAD:main