name: Mirror to Personal Repository

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to personal repository
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Mirror"
          git config --global user.email "actions@github.com"
          # 環境変数を使用してトークンを参照
          echo "Setting up remote repository..."
          git remote add personal https://${TOKEN}@github.com/shimaf4979/mmm.git
          echo "Pushing to personal repository..."
          git push --force "https://${TOKEN}@github.com/shimaf4979/mmm.git" HEAD:main