name: Mirror to Personal Repository

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Debug info
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Push to personal repository
        # 重要: secrets.PERSONAL_TOKENを直接参照するように変更
        run: |
          git config --global user.name "GitHub Actions Mirror"
          git config --global user.email "actions@github.com"
          
          echo "Setting up remote repository..."
          # トークンを直接使用（環境変数ではなく）
          git remote add personal https://${{ secrets.PERSONAL_TOKEN }}@github.com/shimaf4979/mmm.git
          
          echo "Pushing to personal repository..."
          # 同様にトークンを直接使用
          git push --force "https://${{ secrets.PERSONAL_TOKEN }}@github.com/shimaf4979/mmm.git" HEAD:main